sshd-container:
  image: sshd-container
  ports:
    - "6000-6200:6000-6200"
  restart: always

openbazaar:
  image: p2pvps/ob-server
  ports:
   - "4001:4001"
   - "4002:4002"
   - "9005:9005"
  volumes:
   - ~/.p2pvps/openbazaar:/var/lib/openbazaar
  restart: always

listing-manager:
  image: listing-manager
  volumes:
    #- ~/.p2pvps/logs/listing-manager:/usr/src/app/log
    #- ~/.p2pvps/auth:/usr/src/app/auth
    - ~/.p2pvps/logs/listing-manager:/home/p2pvps/logs
    - ~/.p2pvps/auth:/home/p2pvps/auth
  links:
    - p2pvps-server
    - openbazaar
  restart: always

mongodb:
  image: mongo
  ports:
    - "3500:27017"
  volumes:
    - ./data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

p2pvps-server:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb
    - openbazaar
  ports:
    - "3001:5000"  # p2pvps-server2 serves website on this port
    - "9228:9229"  # Node v8 inspector runs on this port
  volumes:
#    - ./theme:/home/connextcms/theme
#    - ./plugins:/home/connextcms/plugins
#    - ./public:/home/connextcms/public
    - ~/.p2pvps/logs/p2pvps-server:/home/p2pvps/logs
#    - ./persist:/home/p2pvps/p2pvps-server2/persist
    - ~/.p2pvps/auth:/home/p2pvps/p2pvps-server2/persist
  restart: always
