#!/bin/bash
#This script file runs any final setup before finalizing the Docker image.

echo Making final preparations to the container. This will take a minute...

#Change owner of the mounted volumes. This must happen in the shells script as it will
#not work inside the Dockerfile.
echo 'password' | sudo -S pwd
sudo chown -R connextcms /home/connextcms

#Final setup script. Executed at the end of the Dockerimage to do final setup.
#Customize this script to execute and plugin or site merge scripts.
cd
cd connextCMS
./copy-keystone
./merge-connextcms-keystone
cd
cd myCMS
echo 'Preparing to run npm install'
npm install
npm install --save winston
cp ~/keystone.js .
cp ~/dummyapp.js .
