#!/bin/bash

# Initialize OpenBazaar
sudo rm -rf ~/.p2pvps/openbazaar/*
docker run --rm -v ~/.p2pvps/openbazaar:/var/lib/openbazaar p2pvps/ob-server:071518 init -d /var/lib/openbazaar
sudo cp open-bazaar/config-071518 ~/.p2pvps/openbazaar/

