#!/bin/bash

# Prep OpenBazaar
#mkdir open-bazaar/data

# Create a data directory
mkdir ~/.p2pvps
mkdir ~/.p2pvps/logs
mkdir ~/.p2pvps/logs/listing-manager
mkdir ~/.p2pvps/openbazaar
mkdir ~/.p2pvps/logs/p2pvps-server
mkdir ~/.p2pvps/auth
