#!/bin/bash

# Ensure bash scripts are executable.
chmod 775 finalsetup
chmod 775 merge-site-plugin-files
chmod 775 mergeandlaunch

# Make needed directories
mkdir public
mkdir theme
mkdir theme/site-template-connextcms
mv merge-site-plugin-files public/

# Prep OpenBazaar
mkdir open-bazaar/data

# Create a data directory
mkdir ~/.p2pvps
mkdir ~/.p2pvps/logs
mkdir ~/.p2pvps/logs/listing-manager
mkdir ~/.p2pvps/openbazaar
mkdir ~/.p2pvps/logs/p2pvps-server
mkdir ~/.p2pvps/auth
