#!/bin/bash
docker run --rm --name ob-server -p 4001:4001 -p 4002:4002 -p 9005:9005 -v ~/.p2pvps/openbazaar:/var/lib/openbazaar ob-server go run openbazaard.go init -d /var/lib/openbazaar/
sudo chown -R ${USER} ~/.p2pvps/openbazaar

